### PR TITLE
allow multiple forwards separated by |

### PR DESCRIPTION
**Pull request by kminek**
`export SMF_CONFIG='contact@somedomain.com:address1@otherdomain.com|address1@otherdomain.com'`

### CODE REVIEW

**Comment by zixia** [comment]
great, thanks for your contribute!

could you modify README for this new feature?

**Comment by kminek** [comment]
done

**Comment by zixia** [comment]
awesome, merged. :+1: 

the docker image on docker hub should be update automaticly,  which tagged by `latest`

**Comment by zixia** [comment]
@kminek had you tried to use "," support multi destination address?

> You can specify multiple forwarding emails by separating them by semicolons. from1@domain:to@target:password;from2@domain:to@target. - https://kiani.io/blog/custom-domain-mail-forward

If "," works, I think "|" is no more needed.

**Comment by kminek** [comment]
> if "," works, I think "|" is no more needed

`semicolon !== comma` :)

**Comment by zixia** [comment]
ok. I have neither tried semicolon nor comma, however I feel comma is more natual, because when we send email, we can use comma in "To" or "Cc".

maybe to support "|" and ";" and "," at the same time is a good idea?

**Comment by kminek** [comment]
i picked `|` because `;` and `:` symbols were already used and performed their role in the process of translating this big string into config file :) but i agree that `,` is more natural so i'm ok with the switch :)

**Pull request merged**
